#!/bin/sh
# Clue runtime loader
#
# © 2008 David Given.
# Clue is licensed under the Revised BSD open source license. To get the
# full license text, see the README file.
#
# $Id$
# $HeadURL$
# $LastChangedDate: 2008-09-07 12:39:58 +0100 (Sun, 07 Sep 2008) $

set -e

TEMPFILE=`mktemp`
trap "rm -f $TEMPFILE" 0

validate_engine() {
	case "$1" in
		lua)
			which lua > /dev/null
			return $?
			;;
			
		luajit)
			which luajit > /dev/null
			return $?
			;;
			
		smjs)
			which smjs > /dev/null
			return $?
			;;
			
		rhino)
			which rhino > /dev/null
			return $?
			;;
			
		c)
			which gcc > /dev/null
			return $?
			;;
			
		perl5)
			which perl > /dev/null
			return $?
			;;

		sbcl)
			which sbcl > /dev/null
			return $?
			;;
	esac
	
	return 1
}

execute_engine() {
	case "$1" in
		lua)
			exec lua src/lua/run.lua -- "$@"
			;;
			
		luajit)
			exec luajit -O src/lua/run.lua -- "$@"
			;;
			
		smjs)
			exec smjs src/javascript/run.js "$@"
			;;
			
		rhino)
			exec rhino src/javascript/run.js "$@"
			;;
			
		perl5)
			exec perl src/perl5/run.pl "$@"
			;;
			
		c)
			shift
			infiles=
			while [ "$1" != "--" ]; do
				infiles="$infiles $1"
				shift
			done
			
			gcc --std=c99 -g -Os -I src/c $infiles src/c/crt.c src/c/libc.c -lm -o $TEMPFILE

			shift
			shift
			exec $TEMPFILE "$@"
			;;			

		sbcl)
			exec sbcl --noinform --load src/lisp/run.lisp --no-userinit --end-toplevel-options "$@"
			;;
	esac
	
	echo "cluerun: unknown engine $1" 1>&2
	exit 1
}

inputfiles=
engine=
while [ "$1" != "" ]; do
	case "$1" in
		-h|--help)
			echo "cluerun: no help yet." 1>&2
			exit 1
			;;
			
		-f|--file)
			inputfiles="$inputfiles $2"
			shift
			;;
			
		-e|--engine)
			engine="$2"
			shift
			;;
			
		--)
			shift
			break
			;;
			
		*)
			echo "cluerun: unrecognised option $1" 1>&2
			exit 1
			;;
	esac
	shift 
done

if [ "$engine" = "" ]; then
	case "$inputfiles" in
		*.luac)
			engine=luajit
			;;
			
		*.js)
			engine=smjs
			;;
			
		*.pl)
			engine=perl5
			;;
		
		*.c)
			engine=c
			;;
			
		*.lisp)
			engine=sbcl
			;;
			
		*)
			echo "cluerun: unable to guess engine type; try -e" 1>&2
			exit 1
			;;
	esac
fi

if ! validate_engine $engine; then
	echo "cluerun: engine '$engine' doesn't seem to be available" 1>&2
	exit 1
fi

execute_engine $engine $inputfiles -- clue "$@"
